name: Next.js CI/CD Pipeline

on:
  push:
    branches:
      - final_deliverables

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.18.2'

    - name: Install dependencies
      run: npm install

    - name: Build
      env:
        NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
        NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
      run: npm run build

    - name: Deploy to Server
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SERVER_IP: 15.184.4.64
        SERVER_USER: ubuntu
        DEPLOY_PATH: /home/ubuntu/webpulse
      run: |
        echo "$SSH_PRIVATE_KEY" > privatekey.pem
        chmod 600 privatekey.pem
        rsync -avz -e "ssh -i privatekey.pem -o StrictHostKeyChecking=no" --exclude=node_modules --exclude=.git ./ $SERVER_USER@$SERVER_IP:$DEPLOY_PATH
        ssh -i privatekey.pem -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP << 'EOF'
          cd $DEPLOY_PATH
          npm install --production
          pm2 restart webpulse || pm2 start npm --name "webpulse" -- start
        EOF
